### ISSUE TITLE
didFailToRegisterForRemoteNotificationsWithError getting error.

### ISSUE THREAD

**Issue by seropusha** [pixeldock/PushNotificationUITests#1]
I'm use APNS Certificates, change bundle and load all dependencies and
your code not call application(_ application:,get deviceToken:) and token didn’t set in appeared UILabel.
And get error in application(_ application:, didFailToRegisterForRemoteNotificationsWithError error:).
As result are tests failed.
"Failed to register: Error Domain=NSCocoaErrorDomain Code=3010 “remote notifications are not supported in the simulator”

**Comment by pixeldock** [comment]
Push Notifications don‘t work on the Simulator. You need to run it on an actual iPhone.
